package io.github.maslke.dwg.support;

public class DwgObjectType {
  public static final int DWG_TYPE_UNUSED = 0x00;
  public static final int DWG_TYPE_TEXT = 0x01;
  public static final int DWG_TYPE_ATTRIB = 0x02;
  public static final int DWG_TYPE_ATTDEF = 0x03;
  public static final int DWG_TYPE_BLOCK = 0x04;
  public static final int DWG_TYPE_ENDBLK = 0x05;
  public static final int DWG_TYPE_SEQEND = 0x06;
  public static final int DWG_TYPE_INSERT = 0x07;
  public static final int DWG_TYPE_MINSERT = 0x08;
  // DWG_TYPE_TRACE_old = 0x09, /* old TRACE r10-r11 only */
  public static final int DWG_TYPE_VERTEX_2D = 0x0a;
  public static final int DWG_TYPE_VERTEX_3D = 0x0b;
  public static final int DWG_TYPE_VERTEX_MESH = 0x0c;
  public static final int DWG_TYPE_VERTEX_PFACE = 0x0d;
  public static final int DWG_TYPE_VERTEX_PFACE_FACE = 0x0e;
  public static final int DWG_TYPE_POLYLINE_2D = 0x0f;
  public static final int DWG_TYPE_POLYLINE_3D = 0x10;
  public static final int DWG_TYPE_ARC = 0x11;
  public static final int DWG_TYPE_CIRCLE = 0x12;
  public static final int DWG_TYPE_LINE = 0x13;
  public static final int DWG_TYPE_DIMENSION_ORDINATE = 0x14;
  public static final int DWG_TYPE_DIMENSION_LINEAR = 0x15;
  public static final int DWG_TYPE_DIMENSION_ALIGNED = 0x16;
  public static final int DWG_TYPE_DIMENSION_ANG3PT = 0x17;
  public static final int DWG_TYPE_DIMENSION_ANG2LN = 0x18;
  public static final int DWG_TYPE_DIMENSION_RADIUS = 0x19;
  public static final int DWG_TYPE_DIMENSION_DIAMETER = 0x1A;
  public static final int DWG_TYPE_POINT = 0x1b;
  public static final int DWG_TYPE__3DFACE = 0x1c;
  public static final int DWG_TYPE_POLYLINE_PFACE = 0x1d;
  public static final int DWG_TYPE_POLYLINE_MESH = 0x1e;
  public static final int DWG_TYPE_SOLID = 0x1f;
  public static final int DWG_TYPE_TRACE = 0x20;
  public static final int DWG_TYPE_SHAPE = 0x21;
  public static final int DWG_TYPE_VIEWPORT = 0x22;
  public static final int DWG_TYPE_ELLIPSE = 0x23;
  public static final int DWG_TYPE_SPLINE = 0x24;
  public static final int DWG_TYPE_REGION = 0x25;
  public static final int DWG_TYPE__3DSOLID = 0x26;
  public static final int DWG_TYPE_BODY = 0x27;
  public static final int DWG_TYPE_RAY = 0x28;
  public static final int DWG_TYPE_XLINE = 0x29;
  public static final int DWG_TYPE_DICTIONARY = 0x2a;
  public static final int DWG_TYPE_OLEFRAME = 0x2b;
  public static final int DWG_TYPE_MTEXT = 0x2c;
  public static final int DWG_TYPE_LEADER = 0x2d;
  public static final int DWG_TYPE_TOLERANCE = 0x2e;
  public static final int DWG_TYPE_MLINE = 0x2f;
  public static final int DWG_TYPE_BLOCK_CONTROL = 0x30;
  public static final int DWG_TYPE_BLOCK_HEADER = 0x31;
  public static final int DWG_TYPE_LAYER_CONTROL = 0x32;
  public static final int DWG_TYPE_LAYER = 0x33;
  public static final int DWG_TYPE_STYLE_CONTROL = 0x34; /* 52 SHAPEFILE_CONTROL */
  public static final int DWG_TYPE_STYLE = 0x35;
  /* DWG_TYPE_<UNKNOWN> = 0x36, */
  /* DWG_TYPE_<UNKNOWN> = 0x37, */
  public static final int DWG_TYPE_LTYPE_CONTROL = 0x38;
  public static final int DWG_TYPE_LTYPE = 0x39;
  /* DWG_TYPE_<UNKNOWN> = 0x3a, */
  /* DWG_TYPE_<UNKNOWN> = 0x3b, */
  public static final int DWG_TYPE_VIEW_CONTROL = 0x3c;
  public static final int DWG_TYPE_VIEW = 0x3d;
  public static final int DWG_TYPE_UCS_CONTROL = 0x3e;
  public static final int DWG_TYPE_UCS = 0x3f;
  public static final int DWG_TYPE_VPORT_CONTROL = 0x40;
  public static final int DWG_TYPE_VPORT = 0x41;
  public static final int DWG_TYPE_APPID_CONTROL = 0x42;
  public static final int DWG_TYPE_APPID = 0x43;
  public static final int DWG_TYPE_DIMSTYLE_CONTROL = 0x44;
  public static final int DWG_TYPE_DIMSTYLE = 0x45;
  public static final int DWG_TYPE_VX_CONTROL = 0x46;
  public static final int DWG_TYPE_VX_TABLE_RECORD = 0x47;
  public static final int DWG_TYPE_GROUP = 0x48;
  public static final int DWG_TYPE_MLINESTYLE = 0x49;
  public static final int DWG_TYPE_OLE2FRAME = 0x4a;
  public static final int DWG_TYPE_DUMMY = 0x4b;
  public static final int DWG_TYPE_LONG_TRANSACTION = 0x4c;
  public static final int DWG_TYPE_LWPOLYLINE = 0x4d; /* ?? */
  public static final int DWG_TYPE_HATCH = 0x4e;
  public static final int DWG_TYPE_XRECORD = 0x4f;
  public static final int DWG_TYPE_PLACEHOLDER = 0x50;
  public static final int DWG_TYPE_VBA_PROJECT = 0x51;
  public static final int DWG_TYPE_LAYOUT = 0x52;

  public static final int DWG_TYPE_PROXY_ENTITY = 0x1f2; /* 498 */
  public static final int DWG_TYPE_PROXY_OBJECT = 0x1f3; /* 499 */
}
